services:
  postgres:
    image: postgres:16-alpine
    container_name: csmju_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csmju_coop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge